### ISSUE TITLE
keys longer than 32767 bytes cause undefined behaviour

### ISSUE THREAD

**Issue by mjakubicek** [dcjones/hat-trie#30]
Passing in keys longer than 32767 bytes causes all kind of undefined behaviour (e.g. segfault) when iterating over the hat-trie later.

Valgrind indicates the following:

==20614== Memcheck, a memory error detector
==20614== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==20614== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==20614== Command: ./mkhatlex
==20614== 
len=32768==20614== Invalid write of size 8
==20614==    at 0x4E3996D: ahtable_sorted_iter_begin (ahtable.c:352)
==20614==    by 0x4E3996D: ahtable_iter_begin (ahtable.c:523)
==20614==    by 0x4E3A346: hattrie_iter_nextnode (hat-trie.c:576)
==20614==    by 0x4E3AF9B: hattrie_iter_begin (hat-trie.c:605)
==20614==    by 0x400BD3: main (mkhatlex.c:51)
==20614==  Address 0x542b688 is 0 bytes after a block of size 8 alloc'd
==20614==    at 0x4C2BBAD: malloc (vg_replace_malloc.c:299)
==20614==    by 0x4E3B2A8: malloc_or_die (misc.c:14)
==20614==    by 0x4E398F2: ahtable_sorted_iter_begin (ahtable.c:344)
==20614==    by 0x4E398F2: ahtable_iter_begin (ahtable.c:523)
==20614==    by 0x4E3A346: hattrie_iter_nextnode (hat-trie.c:576)
==20614==    by 0x4E3AF9B: hattrie_iter_begin (hat-trie.c:605)
==20614==    by 0x400BD3: main (mkhatlex.c:51)
==20614== 
==20614== 
==20614== HEAP SUMMARY:
==20614==     in use at exit: 0 bytes in 0 blocks
==20614==   total heap usage: 25 allocs, 25 frees, 180,257 bytes allocated
==20614== 
==20614== All heap blocks were freed -- no leaks are possible
==20614== 
==20614== For counts of detected and suppressed errors, rerun with: -v
==20614== ERROR SUMMARY: 3 errors from 1 contexts (suppressed: 0 from 0)

I can prepare a minimum working example but this should be really easy to reproduce.

**Comment by dcjones** [comment]
Dredging up old issue I realize, but keys longer than 2^15-1 aren't supported by design, but it was a pretty serious bug not to make this explicit.

This follows from the original paper:

> The length of each string is stored in either one or two bytes, with the lead bit used to indicate whether a 7-bit or 15-bit value is present. It is not sensible to store strings of more than 32,768 characters in a hash table, as the cost of hashing will utterly dominate search costs.

I kind of get that rationale, but disagree with it. I think it would be nice to support longer keys, by using a more sophisticated encoding of the key lengths. (Nice comparison of methods here: https://github.com/stoklund/varint).

**Comment by mjakubicek** [comment]
I think it's just fine as it is fixed now (so that people will know what's wrong), but I wonder whether the test which currently is "> 32768" should not be "> 32767".

**Comment by dcjones** [comment]
It actually is! I had immediately realized my mistake after pushing and did a amend commit and force push which didn't show up here. https://github.com/dcjones/hat-trie/commit/01f62d7d800d50035892dafa3fba484bf9c61a7f

**Comment by mjakubicek** [comment]
Great, thanks a lot :)
